# Generated by Django 3.1.7 on 2021-04-16 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
