# Generated by Django 3.1.7 on 2021-04-16 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_album_album'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='title',
            new_name='song',
        ),
    ]
